### ISSUE TITLE
doc-request: how to install

### ISSUE THREAD

**Issue by ahammond** [cathalgarvey/go-minilock#14]
I'm new to golang and I'm guessing this would be obvious to someone experienced, but... how do I build / install this?

**Comment by cathalgarvey** [comment]
Hi Andrew, 
Once you have a go environment configured, installing this is `go get -u github.com/cathalgarvey/go-minilock/minilock-cli`, which should install the `minilock-cli` utility.

I should probably look into 'releases' on Github, to make this easier, because Go still leaves "Go Environment Configuration" as a task for the user..

**Comment by ahammond** [comment]
Thanks! I used homebrew on a mac to install golang. It didn't configure the GOPATH. I also use fish shell, so:

```
mkdir -p ~/gocode/bin
set -Ux GOPATH $HOME/gocode
set -U fish_user_paths $fish_user_paths $GOPATH/bin
go get -u github.com/cathalgarvey/go-minilock/minilock-cli
```

Worked! Thanks!!!

**Comment by cathalgarvey** [comment]
Glad it worked! Happy crypting! :)

October 28, 2016 9:28 PM, "Andrew Hammond"  wrote:
	Thanks! I used homebrew on a mac to install golang. It didn't configure the GOPATH. I also use fish shell, so: 

	mkdir -p ~/gocode/bin set -Ux GOPATH $HOME/gocode set -U fish_user_paths $fish_user_paths $GOPATH/bin go get -u github.com/cathalgarvey/go-minilock/minilock-cli  

	Worked! Thanks!!!
