### ISSUE TITLE
error: Failed to encrypt

### ISSUE THREAD

**Issue by jhautefeuille** [cathalgarvey/go-minilock#2]
Hello, 

I try to test minilock-cli but I've an error.

./main encrypt test.txt nzo@xxx.org julien@xxx.org
Enter password: 
main: error: Failed to encrypt..: illegal base58 data at input byte 2

jeancloud@E5500:~/go-minilock/minilock-cli$ go version
go version go1.5.1 linux/amd64

Thank you.

**Comment by cathalgarvey** [comment]
Hi Julien,

The usage I designed may be a bit confusing here, because it asks you to provide your *own* email, but only the miniLock IDs of the recipients. So what it's complaining about is "julien@xxx.org" which isn't a miniLock ID, it's an email address: miniLock has no repository or means of discovering an ID based on an email, you have to provide the IDs yourself.

So, say that julien@xxx.org's miniLock ID is `fthagnfthagnfthagnfthagn`, the command you want would be:

`go run main.go encrypt test.txt nzo@xxx.org fthagnfthagnfthagnfthagn`

Remember also that your provided email is used as part of the key derivation algorithm, so if you provide a different "sending" email then the sending ID will also be different; recipients will see a totally different sender ID. This does mean that you can send an "anonymous" message to people using a spoofed email and passphrase, which is in no way a problem save that the miniLock file won't be authenticateable to any particular sender by the recipient. That is, the recipient cannot know whether the message was sent by someone they trust.

Hope that helps!
